/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eczaneapplication;

import com.mysql.cj.xdevapi.Table;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mert Çebi
 */
public class Medicine extends javax.swing.JFrame {
    
    

    /**
     * Creates new form Medicine
     */
    public Medicine() {
        initComponents();
        
        transferfortable();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        barcode_field = new javax.swing.JTextField();
        medicine_field = new javax.swing.JTextField();
        protocol_field = new javax.swing.JTextField();
        formula_field = new javax.swing.JTextField();
        stock_field = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setText("BARCODE");

        jLabel2.setText("MEDICINE NAME");

        jLabel3.setText("PROTOCOL NO");

        jLabel4.setText("FORMULA");

        jLabel5.setText("STOCK");

        barcode_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barcode_fieldActionPerformed(evt);
            }
        });

        medicine_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicine_fieldActionPerformed(evt);
            }
        });

        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Barcode", "Medicine Name", "Protocol No", "Formula", "Stock"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jButton1.setText("Ekle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Düzenle");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("Sil");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(barcode_field)
                            .addComponent(medicine_field)
                            .addComponent(protocol_field)
                            .addComponent(formula_field)
                            .addComponent(stock_field, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(barcode_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(medicine_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(protocol_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(formula_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(stock_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(0, 48, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Connection connecti = null;
    Connection getConnection() throws SQLException{
        try {
            connecti = DriverManager.getConnection("jdbc:mysql://localhost:3306/eczane?useUnicode=true&characterEncoding=utf8","root","");
            System.out.println("Connection is Successful");
            return connecti;
            }catch (SQLException s) {
            System.out.println("Connection is UNSUCCESSFUL!");
            System.out.println(s);
            return null;
    }
    }
    private void barcode_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barcode_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barcode_fieldActionPerformed

    private void medicine_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicine_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicine_fieldActionPerformed



    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 if(Control() == true){
            try {
                Connection connect = getConnection();
                PreparedStatement preparedStatement = connect.prepareStatement("Insert into medicine (Barcode,Medicine_Name,Protocol_No,Formula,Stock) values (?,?,?,?,?)");
                preparedStatement.setString(1, barcode_field.getText());
                preparedStatement.setString(2, medicine_field.getText());
                preparedStatement.setString(3, protocol_field.getText());
                preparedStatement.setString(4, formula_field.getText());
                preparedStatement.setString(5, stock_field.getText());
                preparedStatement.executeUpdate();   
                JOptionPane.showMessageDialog(null, "İlac Eklendi..");
                transferfortable();
              
                barcode_field.setText("");
                medicine_field.setText("");
                protocol_field.setText("");
                formula_field.setText("");
                stock_field.setText("");
                } catch (Exception e) {
                System.out.println(e);
            }// TODO add your handling code here:
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked
        // TODO add your haint index = Table.getSelectedRow();
        int indexx = jTable2.getSelectedRow();
        try {
            showmedicine(indexx);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jScrollPane2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(!barcode_field.equals("")){
            try {
                Connection connect = getConnection();
                PreparedStatement preparedStatement = connect.prepareStatement("Delete From medicine where Barcode = ?");
                
               int ssn_fieldee = Integer.parseInt(barcode_field.getText());
            preparedStatement.setInt(1, ssn_fieldee);
            preparedStatement.executeUpdate();
            transferfortable();
            JOptionPane.showMessageDialog(null, "Patience deleted");
              
                barcode_field.setText("");
                medicine_field.setText("");
                protocol_field.setText("");
                formula_field.setText("");
                stock_field.setText("");
                } catch (Exception e) {
                System.out.println(e);
            }// TODO add your handling code here:
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        // TODO add your haint index = Table.getSelectedRow();
        int indexx = jTable2.getSelectedRow();
        try {
            showmedicine(indexx);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
         {
            try {
                Connection connect = getConnection();
                PreparedStatement preparedStatement = connect.prepareStatement("Update medicine SET Medicine_Name = ?,Protocol_no = ?,Formula = ?,Stock = ? where Barcode = ?");
                preparedStatement.setInt(5, Integer.valueOf(barcode_field.getText()));
               
                
                preparedStatement.setString(1, medicine_field.getText());
                preparedStatement.setString(2, protocol_field.getText());
                preparedStatement.setString(3, formula_field.getText());
                preparedStatement.setString(4, stock_field.getText());
                preparedStatement.executeUpdate();   
                transferfortable();
                JOptionPane.showMessageDialog(null, "Bilgiler güncellendi");
              
                barcode_field.setText("");
                medicine_field.setText("");
                protocol_field.setText("");
                formula_field.setText("");
                stock_field.setText("");
                } catch (Exception e) {
                System.out.println(e);
            }// TODO add your handling code here:
            
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    
    
    
    
     
    
    
    ArrayList<ilac>getmedicine() throws SQLException{
        ArrayList<ilac> medicinelist = new ArrayList<>();
        Connection connect = getConnection();
        String query = "Select * From medicine";
        Statement statement;
        try {
            ResultSet resultSet;
            statement = connect.createStatement();
            resultSet = statement.executeQuery(query);
            ilac ilc;
            while(resultSet.next()){
                ilc = new ilac(resultSet.getInt("Barcode"),resultSet.getString("Medicine_Name"),resultSet.getInt("Protocol_no"),resultSet.getString("Formula"),resultSet.getInt("Stock"));
                medicinelist.add(ilc);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return medicinelist;
    }
    boolean Control(){
        if(barcode_field.getText() == null || medicine_field.getText() == null || protocol_field.getText() == null || formula_field.getText() == null || stock_field.getText() == null ){
            return false;
        }
        else{
            return true;
        }
    }
     void transferfortable() {
    try {
            ArrayList<ilac>List =getmedicine();
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            model.setRowCount(0);
            Object [] row = new Object[5];
            for(int i = 0;i<List.size();i++){
                row[0] = List.get(i).getBarcode();
                row[1] = List.get(i).getMedicine_Name();
                row[2] = List.get(i).getProtocol_no();
                row[3] = List.get(i).getFormula();
                row[4] = List.get(i).getStock();
                
              model.addRow(row);
                 
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
     
     void showmedicine(int indexx){
        try {
            barcode_field.setText(Integer.toString(getmedicine().get(indexx).getBarcode()));
            medicine_field.setText(getmedicine().get(indexx).getMedicine_Name());
            protocol_field.setText(Integer.toString(getmedicine().get(indexx).getProtocol_no()));
            formula_field.setText(getmedicine().get(indexx).getFormula());
            stock_field.setText(Integer.toString(getmedicine().get(indexx).getStock()));
           
        } catch (Exception e) {
            e.printStackTrace();
        }
         
         
         
    }    

    
    
    
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Medicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Medicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Medicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Medicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Medicine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barcode_field;
    private javax.swing.JTextField formula_field;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField medicine_field;
    private javax.swing.JTextField protocol_field;
    private javax.swing.JTextField stock_field;
    // End of variables declaration//GEN-END:variables

    }

